# Site settings
title: Prognostic Data Solutions - Blog
email: evan@prognosticdatasolutions.com
description:
url: "http://www.prognosticdatasolutions.com" # the base hostname & protocol for your site
twitter_username: Evan_Coop
github_username:  ecooper2

# Build settings
markdown: kramdown
permalink: "/blog/:title"
